### PR TITLE
allowing system calls which need super-user capabilities

### PR DESCRIPTION
**Pull request by francois-dorin**
## Problem

This PR is a proposal to fix issue #19 (Administration area inaccessible with a fresh install)

## Solution

A fresh installation of redmine require some privileges system calls. I just allow them by removing @privileges restriction in SystemCallFilter in the systemd unit.

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
